"""
Django settings for PROJECT_NAME project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os


APP_NAME = 'demo'
PROJECT_NAME = 'chatbot'

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'kbccn9k*#*@7)qy2779r!8yk5%x5v4le5ofm_3t69h8iv!2dju'

# SECURITY WARNING: don't run with debug turned on in production!


DEBUG = False

FORMAT_MODULE_PATH = 'chatbot.formats'

#全ホストを許可
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    APP_NAME,

]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]


ROOT_URLCONF = PROJECT_NAME + '.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = PROJECT_NAME + '.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'chatbotdemo',
        'USER':'demochat',
        'PASSWORD':'demochat',
        'HOST':'localhost',
        'PORT':'3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
#
STATIC_URL = '/static/'

APP_DIR=os.path.join(BASE_DIR, APP_NAME)
STATICFILES_DIR=os.path.join(APP_DIR, 'static')
LOGFILE_DIR = os.path.join(APP_DIR, 'log')
FILE_UPLOAD_TEMP_DIR = os.path.join(APP_DIR, 'temp')

FILE_UPLOAD_MAX_MEMORY_SIZE = 0
TEMP_FILE_NAME = 'temp.xlsx'

# AUTH SETTINGS
LOGIN_ERROR_URL = '/'
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = ''
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


#LOG出力
LOGGING = {
	'version': 1,   
	'formatters': { 
		'detail': {    
			'format': '\t'.join([
				"[%(asctime)s]",
				"%(levelname)s",
				"%(clientip)s",
				"%(user)-8s",
				"Module : %(module)s",
				"  %(message)s",
			])
		},
		'simple': {    
			'format': '[%(levelname)s] %(message)s'
		},
	},
	'handlers': {
		'file': {
			'level': 'DEBUG',  
			'class': 'logging.FileHandler',  
			'filename': os.path.join(LOGFILE_DIR, 'Application.log'),  
			'formatter': 'detail',  
		},
		'console': { 
			'level': 'DEBUG',
			'class': 'logging.StreamHandler',
			'formatter': 'detail'
		},
	},
	'loggers': {
		'simplelogger': {
			'handlers': ['file'],
			'level': 'INFO',
		},
	},
}

